[profile.default]
src = "solidity/src"
out = "solidity/out"
cache_path = "solidity/cache"
libs = [ "solidity/lib" ]
remappings = [
  "@openzeppelin/contracts/=solidity/lib/openzeppelin-contracts/contracts/",
]

# Enable optimizations
optimizer      = true
optimizer_runs = 200

# Enable FFI for deployment scripts
ffi = true

# Gas reporting
gas_reports = [ "*" ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
