[profile.default]
root = "solidity"
src = "src"
libs = [ "lib" ]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
]

# Enable optimizations
optimizer      = true
optimizer_runs = 200

# Enable FFI for deployment scripts
ffi = true

# Gas reporting
gas_reports = [ "*" ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
