moniker = "test-0"
ethereum_config.execution_authrpc_address = "http://<RETH_IP>:8545"
ethereum_config.engine_authrpc_address = "http://<RETH_IP>:8551"
ethereum_config.jwt_token_path = "/home/emerald/jwt"
ethereum_config.eth_genesis_path="./assets/genesis.json"
el_node_type = "archive"
retry_config.initial_delay = "100ms"
retry_config.max_delay = "2s"
retry_config.max_elapsed_time = "20s"
fee_recipient = "0x4242424242424242424242424242424242424242"
num_certificates_to_retain = 64000
num_temp_blocks_retained = 0
prune_at_block_interval = 5

[retry_config]
initial_delay = "100ms"
max_delay = "5s"
max_elapsed_time = "30s"
multiplier = 2.0
