global:
  scrape_interval: 1s
scrape_configs:
  - job_name: "reth0"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:9000"]
        labels:
          client_name: "reth"
          client_type: "execution"
  - job_name: "reth1"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:9001"]
        labels:
          client_name: "reth"
          client_type: "execution"
  - job_name: "reth2"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:9002"]
        labels:
          client_name: "reth"
          client_type: "execution"
  - job_name: "reth3"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:9003"]
        labels:
          client_name: "reth"
          client_type: "execution"
  - job_name: "reth4"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:9004"]
        labels:
          client_name: "reth"
          client_type: "execution"
  - job_name: "reth5"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:9005"]
        labels:
          client_name: "reth"
          client_type: "execution"
  - job_name: "reth6"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:9006"]
        labels:
          client_name: "reth"
          client_type: "execution"
  - job_name: "reth7"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:9007"]
        labels:
          client_name: "reth"
          client_type: "execution"

  - job_name: "malachite0"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:29000"]
        labels:
          client_name: "malachite"
          client_type: "consensus"
  - job_name: "malachite1"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:29001"]
        labels:
          client_name: "malachite"
          client_type: "consensus"
  - job_name: "malachite2"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:29002"]
        labels:
          client_name: "malachite"
          client_type: "consensus"
  - job_name: "malachite3"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:29003"]
        labels:
          client_name: "malachite"
          client_type: "consensus"
  - job_name: "malachite4"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:29004"]
        labels:
          client_name: "malachite"
          client_type: "consensus"
  - job_name: "malachite5"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:29005"]
        labels:
          client_name: "malachite"
          client_type: "consensus"
  - job_name: "malachite6"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:29006"]
        labels:
          client_name: "malachite"
          client_type: "consensus"
  - job_name: "malachite7"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:29007"]
        labels:
          client_name: "malachite"
          client_type: "consensus"
